spring.application.name=back
server.port=8080

# DBConnection: DataSource 설정
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# 우리가 만든 db(topick)와 연결
spring.datasource.url=jdbc:mysql://localhost:3306/topick?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mysql



#Multipart---------------------------------------------------------------
# spring.servlet.multipart.max-file-size=100MB
# => 요청 받을 수 있는 파일의 최대 사이즈
# spring.servlet.multipart.max-request-size=100MB
# => 요청 받을 수 있는 데이터 전체의 최대 사이즈

# ** Hibernate 설정------------------------------------------------------
spring.jpa.hibernate.ddl-auto=validate
# => 프로젝트 실행시 자동 DDL 생성할것인지 결정여부
#    - create: 매번 Table을 새로 생성
#    - update: 존재하지 않으면 Create, 변경 사항이 있으면 Alter로 자동변경
#    - create-drop: 프로그램 시작시 create 하고 종료 시 drop
#    - validate: 테이블 내용이 변경되면 변경 내용을 출력하고 프로그램 종료  
# => 팀 프로젝트 개발환경 에서는 
#     - 다양한 제약조건들을 사용하게 되고, DDL은 직접 관리하는것이 바람직함 
#    - JPA가 자동으로 제어하게되면 의도하지 않은 변경이 발생하게되어 관리가 어려움.


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
# => hibernate 가 만드는 SQL구문을 콘솔에 formatting(가독성좋게 줄바꿈)하여 보여줌

# ** Hibernate Dialect(사투리,방언) 설정 
# => ORM 프레임웤의 가장큰 특징은 SQL구문을 자동생성하는 것이고
#     이것을 위해 최적화된 SQL구문을 제공하기위해 DBMS별 Dialect 클래스를 제공함
#    - DBMS별 Dialect 클래스의 예
#    - Oracle 12g    : org.hibernate.dialect.Oracle12cDialect
#    - Oracle(모든버전) : org.hibernate.dialect.OracleDialect
#    - MySQL 5.x     : org.hibernate.dialect.MySQL5Dialect
#    - DB2           : org.hibernate.dialect.DB2Dialect
#    - Sybase Anywhere:org.hibernate.dialect.SybaseAnywhereDialect
#
# => SpringBoot 에서는 따로 설정하지 않아도됨 (참고용)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# JPA Test 시 시간이 안맞는경우 시간설정
# => JVM 과 MySql 시간설정이 달라서 발생함
spring.jackson.time-zone=Asia/Seoul
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul


# 26.4.17 (금) Logger, @Log4j2 공부----------------------------------------
#  [ Logging Setting ]
# => INFO, DEBUG, TRACE 변경 Test 
# => 전체 로그레벨 설정 (필요시에만 사용)
# logging.level.root=info
# => com.example.demo 패키지 이하 로그레벨 설정
logging.level.com.example.demo=INFO
logging.level.org.hibernate=info 
                            #대소문자 구분 없�

# Kakao Maps JavaScript key (set your real key here)
kakao.maps.js-key=34eb3cc6da402c74132c932f6bc23ed1

# Kakao REST API key for geocoding (address -> lat/lng)
kakao.rest-api-key=c94c2ec7d389979775650874d197500d